In [1]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.9.0+cu126


# 1. Embedding Layer로 토큰 ID를 벡터로 바꾸기

In [2]:
# 예시 토큰 ID
idx = torch.tensor([2, 3, 1])

# 임베딩 행렬 크기: 가장 큰 토큰 ID + 1
num_idx = max(idx) + 1
out_dim = 5  # 임베딩 차원은 내가 정하는 하이퍼파라미터

torch.manual_seed(123)
embedding = torch.nn.Embedding(num_idx, out_dim)

In [3]:
embedding.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  1.5810],
        [ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015],
        [ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953]], requires_grad=True)

In [5]:
embedding(torch.tensor([1]))

tensor([[ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015]],
       grad_fn=<EmbeddingBackward0>)

# 2. Linear Layer로 같은 걸 해보기

In [6]:
onehot = torch.nn.functional.one_hot(idx)
print(onehot)ㄴ

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])


In [7]:
torch.manual_seed(123)
linear = torch.nn.Linear(num_idx, out_dim, bias=False)

# 임베딩 weight를 Linear에 그대로 복사
linear.weight = torch.nn.Parameter(embedding.weight.T)

linear(onehot.float())

tensor([[ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953],
        [ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015]], grad_fn=<MmBackward0>)